- platform: group
  name: Interior (Test)
  unique_id: interior_test_group
  entities:
    - light.back_stairs_back_stairs
    - light.upstairs_hallway_main_lights
    - light.mudroom_main_lights
    - light.mudroom_nook_lights
    - light.back_patio_light
- platform: group
  name: Foyer
  unique_id: foyer_group
  entities:
    - light.front_foyer_ceiling_lights
    - light.front_foyer_chandelier
    - light.stairs_front_stairs
    - light.vestibule_main_lights
- platform: group
  name: Mudroom
  unique_id: mudroom_group
  entities:
    - light.mudroom_main_lights
    - light.mudroom_nook_lights
- platform: group
  name: Kitchen
  unique_id: kitchen_group
  entities:
    - light.kitchen_main
    - light.kitchen_island
    - light.kitchen_table_lights
    - light.kitchen_sink_light
    - light.kitchen_coffee_bar
- platform: group
  name: Master Bedroom Sconces
  unique_id: master_bedroom_sconces_group
  entities:
    - light.master_bedroom_sconce_l
    - light.master_bedroom_sconce_r
- platform: group
  name: Family Room
  unique_id: family_room_group
  entities:
    - light.family_room_main_lights_1
    - light.family_room_main_lights_2
    - light.family_room_main_lights_3
- platform: group
  name: Wynn's Room
  unique_id: wynns_room_group
  entities:
    - light.wynn_s_room_chandelier
    - light.wynn_s_room_ceiling_lights
