- platform: statistics
  name: "Wine Temperature 24h Stats"
  unique_id: wine_temperature_24h_stats
  entity_id: sensor.wine_temperature
  state_characteristic: mean
  max_age:
    hours: 24
  sampling_size: 1000
  precision: 1

- platform: statistics
  name: "Wine Humidity 24h Stats"
  unique_id: wine_humidity_24h_stats
  entity_id: sensor.wine_humidity
  state_characteristic: mean
  max_age:
    hours: 24
  sampling_size: 1000
  precision: 1

- platform: statistics
  name: "Wine Cave Absolute Humidity 24h Stats"
  unique_id: wine_cave_absolute_humidity_24h_stats
  entity_id: sensor.wine_cave_absolute_humidity
  state_characteristic: mean
  max_age:
    hours: 24
  sampling_size: 1000
  precision: 2

- platform: statistics
  name: "Wine Temperature 7d Stats"
  unique_id: wine_temperature_7d_stats
  entity_id: sensor.wine_temperature
  state_characteristic: mean
  max_age:
    days: 7
  sampling_size: 10000
  precision: 1

- platform: statistics
  name: "Wine Humidity 7d Stats"
  unique_id: wine_humidity_7d_stats
  entity_id: sensor.wine_humidity
  state_characteristic: mean
  max_age:
    days: 7
  sampling_size: 10000
  precision: 1

- platform: statistics
  name: "Wine Temperature 30d Stats"
  unique_id: wine_temperature_30d_stats
  entity_id: sensor.wine_temperature
  state_characteristic: mean
  max_age:
    days: 30
  sampling_size: 10000
  precision: 1

- platform: statistics
  name: "Wine Humidity 30d Stats"
  unique_id: wine_humidity_30d_stats
  entity_id: sensor.wine_humidity
  state_characteristic: mean
  max_age:
    days: 30
  sampling_size: 10000
  precision: 1

- platform: statistics
  name: "Basement Radon 24h Stats"
  unique_id: basement_radon_24h_stats
  entity_id: sensor.basement_air_quality_radon
  state_characteristic: mean
  max_age:
    hours: 24
  sampling_size: 1000
  precision: 0

- platform: statistics
  name: "Basement Radon 7d Stats"
  unique_id: basement_radon_7d_stats
  entity_id: sensor.basement_air_quality_radon
  state_characteristic: mean
  max_age:
    days: 7
  sampling_size: 10000
  precision: 0
